// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type DraftInstanceClassView struct {
	inner baml.ClassBuilder
}

func (t *DraftInstanceClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *DraftInstanceClassView) PropertyStem() (ClassPropertyView, error) {
	return t.inner.Property("stem")
}

func (t *DraftInstanceClassView) PropertyAnswer() (ClassPropertyView, error) {
	return t.inner.Property("answer")
}

func (t *DraftInstanceClassView) PropertyTier() (ClassPropertyView, error) {
	return t.inner.Property("tier")
}

func (t *DraftInstanceClassView) PropertySource_trace() (ClassPropertyView, error) {
	return t.inner.Property("source_trace")
}

func (t *TypeBuilder) DraftInstance() (*DraftInstanceClassView, error) {
	bld, err := t.inner.Class("DraftInstance")
	if err != nil {
		return nil, err
	}
	return &DraftInstanceClassView{inner: bld}, nil
}

func (t *DraftInstanceClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
