// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type InteractionTierEnumView struct {
	inner baml.EnumBuilder
}

func (t *InteractionTierEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *InteractionTierEnumView) ValueA() (EnumValueView, error) {
	return t.inner.Value("A")
}

func (t *InteractionTierEnumView) ValueB() (EnumValueView, error) {
	return t.inner.Value("B")
}

func (t *InteractionTierEnumView) ValueC() (EnumValueView, error) {
	return t.inner.Value("C")
}

func (t *InteractionTierEnumView) ValueD() (EnumValueView, error) {
	return t.inner.Value("D")
}

func (t *TypeBuilder) InteractionTier() (*InteractionTierEnumView, error) {
	bld, err := t.inner.Enum("InteractionTier")
	if err != nil {
		return nil, err
	}
	return &InteractionTierEnumView{inner: bld}, nil
}

func (t *InteractionTierEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
