// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type DraftInstance struct {
	Stem         string          `json:"stem"`
	Answer       string          `json:"answer"`
	Tier         InteractionTier `json:"tier"`
	Source_trace string          `json:"source_trace"`
}

func (c *DraftInstance) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "DraftInstance" {
		panic(fmt.Sprintf("expected DraftInstance, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "stem":
			c.Stem = baml.Decode(valueHolder).Interface().(string)

		case "answer":
			c.Answer = baml.Decode(valueHolder).Interface().(string)

		case "tier":
			c.Tier = baml.Decode(valueHolder).Interface().(InteractionTier)

		case "source_trace":
			c.Source_trace = baml.Decode(valueHolder).Interface().(string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class DraftInstance", key))

		}
	}

}

func (c DraftInstance) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["stem"] = c.Stem

	fields["answer"] = c.Answer

	fields["tier"] = c.Tier

	fields["source_trace"] = c.Source_trace

	return baml.EncodeClass("DraftInstance", fields, nil)
}

func (c DraftInstance) BamlTypeName() string {
	return "DraftInstance"
}
