// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type InteractionTier string

const (
	InteractionTierA InteractionTier = "A"
	InteractionTierB InteractionTier = "B"
	InteractionTierC InteractionTier = "C"
	InteractionTierD InteractionTier = "D"
)

// Values returns all allowed values for the InteractionTier type.
func (InteractionTier) Values() []InteractionTier {
	return []InteractionTier{
		InteractionTierA,
		InteractionTierB,
		InteractionTierC,
		InteractionTierD,
	}
}

// IsValid checks whether the given InteractionTier value is valid.
func (e InteractionTier) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for InteractionTier.
func (e InteractionTier) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid InteractionTier: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for InteractionTier.
func (e *InteractionTier) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = InteractionTier(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid InteractionTier: %q", s)
	}
	return nil
}

func (e *InteractionTier) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "InteractionTier" && name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.InteractionTier, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = InteractionTier(value)
}

func (e InteractionTier) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("InteractionTier", string(e), false)
}

func (e InteractionTier) BamlTypeName() string {
	return "InteractionTier"
}
