// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"generators\\go.baml":            "// Go 生成器：baml_src → ../baml_client（生成物提交入库，纳入 go build/vet）。\r\n// 生成命令（版本锁定，防 codegen 漂移）：\r\n//   npx -y @boundaryml/baml@0.226.1 generate\r\ngenerator target {\r\n  output_type \"go\"\r\n  output_dir \"../\"\r\n  version \"0.226.1\"\r\n  // go.mod module 名（生成内部 import 路径用）\r\n  client_package_name \"github.com/Cloudbird-Software/AI_Web_School\"\r\n  // 生成后立即格式化（GO-1：生成物同样必须 gofmt 零 diff）\r\n  on_generate \"gofmt -w .\"\r\n}\r\n",
	"generators\\lang_sentence.baml": "// W6 语文轮半确定档：句子重组操作员（issue #34 §六三档结构第二档）。\r\n//\r\n// 铁律同 operators.baml（宪法 A2/D10 + issue #34 D-A）：LLM 产出永远是 draft。\r\n// Go 侧 packs/subjectlang.SentenceReorgSolvability 做代码验可解性（独立于 LLM\r\n// 调用面），全过才成实例；任一检查失败即丢弃 draft（draft 永远是 draft）。\r\n// 本文件是本母题 prompt 层唯一事实源；Go 侧经 core/ai Caller 注入出站执行面，\r\n// 测试用 fake Caller，不要求真实 LLM 调用。\r\n\r\n// SentenceReorg 是句子重组 draft 的输出契约（与\r\n// packs/subjectlang.SentenceReorgDraft 的 JSON 字段一一对应）。\r\nclass SentenceReorg {\r\n  sentence string @description(#\"题干句子：围绕题材词写成、适合该学段的一句完整中文句子，句中恰好包含一次挖空词\"#)\r\n  answer string @description(#\"挖空词：句中被挖去的目标词，必须来自入库语料词表（word_in_vocab 判定域）\"#)\r\n  distractors string[] @description(#\"干扰词数组：恰好 3 个，全部在词表内、两两互异、都不等于挖空词、都不出现在题干句中\"#)\r\n  explanation string @description(#\"解析：说明挖空词为何恰配该空格（非空，供评价者核查）\"#)\r\n}\r\n\r\n// GenerateSentenceReorg 依据题材词与学段生成一道「选词填空」草稿。\r\nfunction GenerateSentenceReorg(source_word: string, gradeband: string) -> SentenceReorg {\r\n  client \"openai/gpt-4o-mini\" // 环境变量 OPENAI_API_KEY；与 GenerateDraftInstance 同：不要求真实调用，Go 侧测试用 fake Caller。\r\n  prompt #\"\r\n    你是小学语文练习题生成操作员（半确定档：句子重组）。依据题材词与学段，\r\n    生成一道「选词填空」草稿：一句围绕题材词的完整句子 + 句中挖空词 +\r\n    3 个干扰词 + 解析。\r\n\r\n    规则（Go 侧校验器将逐条复核，任何一条不满足该草稿作废）：\r\n    1. sentence：一句适合该学段学生的完整中文句子，围绕题材词展开；\r\n       句子必须恰好包含一次挖空词。\r\n    2. answer（挖空词）：必须来自入库语料词表。\r\n    3. distractors：恰好 3 个干扰词，全部来自词表；两两互异；都不等于挖空词；\r\n       都不出现在题干句中（避免多解）。\r\n    4. explanation：非空，说明挖空词为何恰配该空格。\r\n\r\n    题材词（source_word）：{{ source_word }}\r\n    学段（gradeband）：{{ gradeband }}\r\n\r\n    {{ ctx.output_format }}\r\n  \"#\r\n}\r\n\r\ntest sentence_reorg_golden {\r\n  functions [GenerateSentenceReorg]\r\n  args {\r\n    source_word \"太阳\"\r\n    gradeband \"L\"\r\n  }\r\n}\r\n",
	"operators.baml":                 "// W5-R 操作员（Operator）最小函数（T-W5-030 spike）。\r\n//\r\n// 铁律（宪法 A2/D10 + issue #34 D-A）：LLM 产出永远是 draft，只有过校验门、\r\n// 经写入服务入账的才是内容版本；内容源只来自入库语料（corpus_version 账），\r\n// LLM 出题不造内容源——结构性杜绝幻觉进题库。\r\n//\r\n// 本文件是 prompt 层唯一事实源（languages.yaml llm_prompt 层：allowed=baml，\r\n// 禁止 prompt 字符串插值进代码）。变更必须过 golden 快照（make baml-golden-check）。\r\n\r\n// 生产线四级（宪法 A7：A/B/C/D 四级输出统一 ItemVersion）。\r\nenum InteractionTier {\r\n  A @description(#\"结构化母题级（可无限实例化的函数库模板）\"#)\r\n  B @description(#\"语料驱动变体级\"#)\r\n  C @description(#\"人工/LLM 单件级草稿\"#)\r\n  D @description(#\"外采入库级\"#)\r\n}\r\n\r\n// Defining a data model.\r\nclass DraftInstance {\r\n  stem string @description(#\"题干（只能使用语料摘录中出现过的实体与措辞）\"#)\r\n  answer string @description(#\"参考答案\"#)\r\n  tier InteractionTier @description(#\"该草稿所属生产线档位\"#)\r\n  source_trace string @description(#\"生成路径说明：母题签名与语料摘录如何进入题干（供评价者核查事实一致性）\"#)\r\n}\r\n\r\n// Create a function to generate a candidate draft instance.\r\nfunction GenerateDraftInstance(template_signature: string, corpus_excerpt: string) -> DraftInstance {\r\n  // 模型档位注册化：供应商/模型与采样参数最终全进 AI 台账（D10）。\r\n  client \"openai/gpt-4o-mini\" // 环境变量 OPENAI_API_KEY；spike 不做真实调用。\r\n  prompt #\"\r\n    你是小学练习题生成操作员。依据母题结构签名与入库语料摘录，生成一个候选实例草稿。\r\n\r\n    规则：\r\n    1. 题干只能使用语料摘录中出现过的实体与措辞，不得引入语料之外的事实。\r\n    2. 保持母题结构签名声明的题型结构与参数槽。\r\n    3. source_trace 必须指明题干的每一处实体来自语料摘录的哪一句。\r\n\r\n    母题结构签名：\r\n    {{ template_signature }}\r\n\r\n    入库语料摘录：\r\n    {{ corpus_excerpt }}\r\n\r\n    {{ ctx.output_format }}\r\n  \"#\r\n}\r\n\r\ntest spike_golden_generate_draft {\r\n  functions [GenerateDraftInstance]\r\n  args {\r\n    template_signature \"{{\\\"interaction\\\":\\\"single_choice\\\",\\\"slots\\\":[\\\"a\\\",\\\"b\\\"]}}\"\r\n    corpus_excerpt #\"\r\n      圆是到定点距离等于定长的点的集合。半径为 3 厘米的圆，直径是 6 厘米。\r\n    \"#\r\n  }\r\n}\r\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
