// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

var file_map = map[string]string{

	"generators/go.baml": "// Go 生成器：baml_src → ../baml_client（生成物提交入库，纳入 go build/vet）。\n// 生成命令（版本锁定，防 codegen 漂移）：\n//   npx -y @boundaryml/baml@0.226.1 generate\ngenerator target {\n  output_type \"go\"\n  output_dir \"../\"\n  version \"0.226.1\"\n  // go.mod module 名（生成内部 import 路径用）\n  client_package_name \"github.com/Cloudbird-Software/AI_Web_School\"\n  // 生成后立即格式化（GO-1：生成物同样必须 gofmt 零 diff）\n  on_generate \"gofmt -w .\"\n}\n",
	"operators.baml":     "// W5-R 操作员（Operator）最小函数（T-W5-030 spike）。\n//\n// 铁律（宪法 A2/D10 + issue #34 D-A）：LLM 产出永远是 draft，只有过校验门、\n// 经写入服务入账的才是内容版本；内容源只来自入库语料（corpus_version 账），\n// LLM 出题不造内容源——结构性杜绝幻觉进题库。\n//\n// 本文件是 prompt 层唯一事实源（languages.yaml llm_prompt 层：allowed=baml，\n// 禁止 prompt 字符串插值进代码）。变更必须过 golden 快照（make baml-golden-check）。\n\n// 生产线四级（宪法 A7：A/B/C/D 四级输出统一 ItemVersion）。\nenum InteractionTier {\n  A @description(#\"结构化母题级（可无限实例化的函数库模板）\"#)\n  B @description(#\"语料驱动变体级\"#)\n  C @description(#\"人工/LLM 单件级草稿\"#)\n  D @description(#\"外采入库级\"#)\n}\n\n// Defining a data model.\nclass DraftInstance {\n  stem string @description(#\"题干（只能使用语料摘录中出现过的实体与措辞）\"#)\n  answer string @description(#\"参考答案\"#)\n  tier InteractionTier @description(#\"该草稿所属生产线档位\"#)\n  source_trace string @description(#\"生成路径说明：母题签名与语料摘录如何进入题干（供评价者核查事实一致性）\"#)\n}\n\n// Create a function to generate a candidate draft instance.\nfunction GenerateDraftInstance(template_signature: string, corpus_excerpt: string) -> DraftInstance {\n  // 模型档位注册化：供应商/模型与采样参数最终全进 AI 台账（D10）。\n  client \"openai/gpt-4o-mini\" // 环境变量 OPENAI_API_KEY；spike 不做真实调用。\n  prompt #\"\n    你是小学练习题生成操作员。依据母题结构签名与入库语料摘录，生成一个候选实例草稿。\n\n    规则：\n    1. 题干只能使用语料摘录中出现过的实体与措辞，不得引入语料之外的事实。\n    2. 保持母题结构签名声明的题型结构与参数槽。\n    3. source_trace 必须指明题干的每一处实体来自语料摘录的哪一句。\n\n    母题结构签名：\n    {{ template_signature }}\n\n    入库语料摘录：\n    {{ corpus_excerpt }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n\ntest spike_golden_generate_draft {\n  functions [GenerateDraftInstance]\n  args {\n    template_signature \"{{\\\"interaction\\\":\\\"single_choice\\\",\\\"slots\\\":[\\\"a\\\",\\\"b\\\"]}}\"\n    corpus_excerpt #\"\n      圆是到定点距离等于定长的点的集合。半径为 3 厘米的圆，直径是 6 厘米。\n    \"#\n  }\n}\n",
}

func getBamlFiles() map[string]string {
	return file_map
}
