// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/Cloudbird-Software/AI_Web_School/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

type parse struct{}

var Parse = &parse{}

// / Parse version of GenerateDraftInstance (Takes in string and returns types.DraftInstance)
func (*parse) GenerateDraftInstance(text string, opts ...CallOptionFunc) (types.DraftInstance, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateDraftInstance: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateDraftInstance", encoded)
	if err != nil {
		return types.DraftInstance{}, err
	}

	casted := (result).(types.DraftInstance)

	return casted, nil
}

// / Parse version of GenerateSentenceReorg (Takes in string and returns types.SentenceReorg)
func (*parse) GenerateSentenceReorg(text string, opts ...CallOptionFunc) (types.SentenceReorg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateSentenceReorg: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateSentenceReorg", encoded)
	if err != nil {
		return types.SentenceReorg{}, err
	}

	casted := (result).(types.SentenceReorg)

	return casted, nil
}
