// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	"github.com/Cloudbird-Software/AI_Web_School/baml_client/types"
	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

func GenerateDraftInstance(ctx context.Context, template_signature string, corpus_excerpt string, opts ...CallOptionFunc) (types.DraftInstance, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"template_signature": template_signature, "corpus_excerpt": corpus_excerpt},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateDraftInstance", encoded, callOpts.onTick)
		if err != nil {
			return types.DraftInstance{}, err
		}

		if result.Error != nil {
			return types.DraftInstance{}, result.Error
		}

		casted := (result.Data).(types.DraftInstance)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateDraftInstance", encoded, callOpts.onTick)
		if err != nil {
			return types.DraftInstance{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.DraftInstance{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.DraftInstance), nil
			}
		}

		return types.DraftInstance{}, fmt.Errorf("No data returned from stream")
	}
}

func GenerateSentenceReorg(ctx context.Context, source_word string, gradeband string, vocab_candidates string, opts ...CallOptionFunc) (types.SentenceReorg, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	// Resolve client option to clientRegistry (client takes precedence)
	if callOpts.client != nil {
		if callOpts.clientRegistry == nil {
			callOpts.clientRegistry = baml.NewClientRegistry()
		}
		callOpts.clientRegistry.SetPrimaryClient(*callOpts.client)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"source_word": source_word, "gradeband": gradeband, "vocab_candidates": vocab_candidates},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		panic(err)
	}

	if callOpts.onTick == nil {
		result, err := bamlRuntime.CallFunction(ctx, "GenerateSentenceReorg", encoded, callOpts.onTick)
		if err != nil {
			return types.SentenceReorg{}, err
		}

		if result.Error != nil {
			return types.SentenceReorg{}, result.Error
		}

		casted := (result.Data).(types.SentenceReorg)

		return casted, nil
	} else {
		channel, err := bamlRuntime.CallFunctionStream(ctx, "GenerateSentenceReorg", encoded, callOpts.onTick)
		if err != nil {
			return types.SentenceReorg{}, err
		}

		for result := range channel {
			if result.Error != nil {
				return types.SentenceReorg{}, result.Error
			}

			if result.HasData {
				return result.Data.(types.SentenceReorg), nil
			}
		}

		return types.SentenceReorg{}, fmt.Errorf("No data returned from stream")
	}
}
